// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrerbjjcmagvrhhgnufh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyZXJiampjbWFndnJoaGdudWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjA4ODgsImV4cCI6MjA2MjY5Njg4OH0.T2KKwTjHPNRJ7c3cQBmReqYOAqRQDFPZcnkK5HMQ5Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);